# Ejercicios Modulo 5. Librerías especializadas en datos (Soluciones)

Consideraciones a tener en cuenta: 

* Guardar este documento con el siguiente formato para su entrega: __M5_05_nombre_apellido1_apellido2__
* Realizar los ejercicios con las herramientas vistas en las sesiones. 
* Comentar el código
* Utilizar nombres de variables apropiados, si vais a guardar una nota, llamar a esa variable nota, no n o x

In [3]:
import pandas as pd

import matplotlib.pyplot as plt
# la siguiente instruccion permite incorporar las graficas en este documento
import  numpy as np

'''
Conozcamos pandas

pandas tiene 3 estructuras de datos principales
DataFrame
Series
Panels (mas avanzada)

DataFrame

es una estructura de datos tabular que se compone de columas y filas ordenadas. Para que todo
se mas sencillo vamos a ver un ejemplo de creacion de un DataFrame(tabla) de un diccionario de
listas. El siguiente Ejemplo muestra un diccionario que consta de dos keys, Name y Age. Y su 
correspondiente lista de valores.
'''

name_age = {

    "Name":["Ali","Bill","David", "Hany","Itsima"],
    "Age" :[32, 55, 20, 43, 30]
}
dataframe =pd.DataFrame(name_age)
dataframe

     Name  Age
0     Ali   32
1    Bill   55
2   David   20
3    Hany   43
4  Itsima   30

**1) Trabajemos con NumPy**

* Importa numpy y usa un alias para poder utilizar sus recursos
* Crea un array de elementos (del 10 al 100)
* Invertir el array
* Crear un array 3x3 con valores de 0 a 8
* Crear un array identidad de 6x6
* Crear un array con valores al azar con forma 3x3x3
* Crear dos arrays con valores al azar A y B, verificar si son iguales (hay varias opciones, investigar)

In [ ]:
import numpy as np

# Crear un array de elementos (del 10 al 100)
array_10_to_100 = np.arange(10, 101)
print("Array del 10 al 100:", array_10_to_100)

# Invertir el array
array_invertido = np.flip(array_10_to_100)
print("Array invertido:", array_invertido)

# Crear un array 3x3 con valores de 0 a 8
array_3x3 = np.arange(9).reshape(3, 3)
print("Array 3x3 con valores de 0 a 8:\n", array_3x3)

# Crear un array identidad de 6x6
array_identidad = np.eye(6)
print("Array identidad de 6x6:\n", array_identidad)

# Crear un array con valores al azar con forma 3x3x3
array_aleatorio = np.random.random((3, 3, 3))
print("Array al azar con forma 3x3x3:\n", array_aleatorio)

# Crear dos arrays con valores al azar A y B
A = np.random.random((3, 3))
B = np.random.random((3, 3))

# Verificar si son iguales
son_iguales = np.array_equal(A, B)
print("¿Los arrays A y B son iguales?:", son_iguales)

**2) Sigamos con NumPy**

* Crear un array de 100 elementos aleatorios comprendidos entre 1 y 1000 (pueden ser números enteros).
* Este array se llamara dólares
* Crear otro array llamado euros
* Realizar la conversión de los precios en dólares del primer array al segundo array en euros. Se puede serguir la siguiente conversión:
    - 1 EUR = 1,14362 USD
    - 1 USD = 0,874413 EUR
* Mostrar el resultado del array de euros pero redondeado a 2 decimales

In [ ]:
import numpy as np

# Crear un array de 100 elementos aleatorios entre 1 y 1000
dolares = np.random.randint(1, 1001, 100)
print("Array de precios en dólares:\n", dolares)

# Crear un array llamado euros
euros = dolares * 0.874413
print("Array de precios en euros:\n", euros)

# Redondear el array de euros a 2 decimales
euros_redondeados = np.round(euros, 2)
print("Array de precios en euros (redondeado a 2 decimales):\n", euros_redondeados)

**3) Trabajemos con pandas**

* Importa pandas y usa un alias para poder utilizar sus recursos
* Cargar como dataframe de pandas el csv 05_05_imdb_titulos.csv y mostrar sus 5 primeros registros
* Cargar como dataframe de pandas el csv 05_05_imdb_elenco.csv y mostrar sus 5 primeros registros
* Mostrar el número de registros del dataframe de titulos
* Mostrar el número de registros del dataframe de elenco
* Mostrar las 5 peliculas más antiguas del listado de titulos
* Mostrar las peliculas que en el titulo tienen la palabra "Dracula". También mostrar el número total de peliculas que coincidan con este requisito
* Mostrar los 10 titulos más comunes (que más se repiten)
* Mostrar cual fue la primer pelicula hecha titulada "Romeo and Juliet" 
* Listar todas las peliculas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
* Mostrar cuantas peliculas fueron hechas en el año 1950
* Mostrar cuantas peliculas fueron hechas de 1950 a 1959
* Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias
* Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
* Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
* Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
* Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
* Mostrar cuantos papeles para actores hubo en la década de los 50's
* Mostrar cuantos papeles para actrices hubo en la década de los 50's

In [ ]:
import pandas as pd

# Cargar como dataframe de pandas el csv 05_05_imdb_titulos.csv y mostrar sus 5 primeros registros
titulos_df = pd.read_csv("05_05_imdb_titulos.csv")
print("Primeros 5 registros del dataframe de títulos:")
print(titulos_df.head())

# Cargar como dataframe de pandas el csv 05_05_imdb_elenco.csv y mostrar sus 5 primeros registros
elenco_df = pd.read_csv("05_05_imdb_elenco.csv")
print("\nPrimeros 5 registros del dataframe de elenco:")
print(elenco_df.head())

# Mostrar el número de registros del dataframe de títulos
num_registros_titulos = len(titulos_df)
print("\nNúmero de registros del dataframe de títulos:", num_registros_titulos)

# Mostrar el número de registros del dataframe de elenco
num_registros_elenco = len(elenco_df)
print("Número de registros del dataframe de elenco:", num_registros_elenco)

# Mostrar las 5 peliculas más antiguas del listado de titulos
peliculas_antiguas = titulos_df.sort_values(by="year").head()
print("\nLas 5 películas más antiguas:")
print(peliculas_antiguas)

# Mostrar las peliculas que en el titulo tienen la palabra "Dracula". También mostrar el número total de peliculas que coincidan con este requisito
dracula_movies = titulos_df[titulos_df["title"].str.contains("Dracula", case=False)]
num_dracula_movies = len(dracula_movies)
print("\nPelículas que contienen la palabra 'Dracula':")
print(dracula_movies)
print("\nNúmero total de películas que contienen la palabra 'Dracula':", num_dracula_movies)

# Mostrar los 10 titulos más comunes (que más se repiten)
titulos_mas_comunes = titulos_df["title"].value_counts().head(10)
print("\nLos 10 títulos más comunes:")
print(titulos_mas_comunes)

# Mostrar cual fue la primer pelicula hecha titulada "Romeo and Juliet" 
primer_romeo_and_juliet = titulos_df[titulos_df["title"] == "Romeo and Juliet"].sort_values(by="year").head(1)
print("\nPrimera película titulada 'Romeo and Juliet':")
print(primer_romeo_and_juliet)

# Listar todas las peliculas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
exorcist_movies = titulos_df[titulos_df["title"].str.contains("Exorcist", case=False)].sort_values(by="year")
print("\nPelículas que contienen la palabra 'Exorcist', ordenadas por año:")
print(exorcist_movies)

# Mostrar cuantas peliculas fueron hechas en el año 1950
num_peliculas_1950 = titulos_df[titulos_df["year"] == 1950].shape[0]
print("\nNúmero de películas hechas en el año 1950:", num_peliculas_1950)

# Mostrar cuantas peliculas fueron hechas de 1950 a 1959
num_peliculas_1950s = titulos_df[(titulos_df["year"] >= 1950) & (titulos_df["year"] <= 1959)].shape[0]
print("Número de películas hechas de 1950 a 1959:", num_peliculas_1950s)

# Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias
roles_godfather = elenco_df[elenco_df["title"] == "The Godfather"]["character"].unique()
num_roles_godfather = len(roles_godfather)
print("\nRoles en la película 'The Godfather':")
print(roles_godfather)
print("\nNúmero total de roles en la película 'The Godfather':", num_roles_godfather)

# Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
elenco_dracula_1958 = elenco_df[(elenco_df["title"] == "Dracula") & (elenco_df["year"] == 1958)].sort_values(by="n")
print("\nElenco completo de la película 'Dracula' de 1958 ordenado por clasificación 'n':")
print(elenco_dracula_1958)

# Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
num_papeles_bruce_wayne = elenco_df[elenco_df["character"] == "Bruce Wayne"].shape[0]
print("\nNúmero de papeles de 'Bruce Wayne' en la historia de las películas:", num_papeles_bruce_wayne)

# Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
num_papeles_robert_de_niro = elenco_df[elenco_df["name"] == "Robert De Niro"].shape[0]
print("\nNúmero de papeles de 'Robert De Niro' en su carrera:", num_papeles_robert_de_niro)

# Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
papeles_protagonista_charlton_heston = elenco_df[(elenco_df["name"] == "Charlton Heston") & (elenco_df["n"] == 1) & (elenco_df["year"] >= 1960) & (elenco_df["year"] <= 1969)].sort_values(by="year", ascending=False)
print("\nPapeles como protagonista de Charlton Heston en los 60's:")
print(papeles_protagonista_charlton_heston)

# Mostrar cuantos papeles para actores hubo en la década de los 50's
num_papeles_actores_50s = elenco_df[(elenco_df["type"] == "actor") & (elenco_df["year"] >= 1950) & (elenco_df["year"] <= 1959)].shape[0]
print("\nNúmero de papeles para actores en la década de los 50's:", num_papeles_actores_50s)

# Mostrar cuantos papeles para actrices hubo en la década de los 50's
num_papeles_actrices_50s = elenco_df[(elenco_df["type"] == "actress") & (elenco_df["year"] >= 1950) & (elenco_df["year"] <= 1959)].